version: "3"

services:
  postgres:
    image: postgres:9.5
    volumes:
      - /var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: always
  cachet:
    build:
      context: .
      args:
        - cachet_ver=v2.3.12
    ports:
      - 80:8000
    links:
      - postgres:postgres
    environment:
      - DB_DRIVER=pgsql
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_PREFIX=chq_
      - APP_KEY=base64:39CNYolIySMPEXCspyUyKLrUnc7bAaVb0lZo42YkMDU=
      - APP_LOG=errorlog
      - DEBUG=false
      - MAIL_DRIVER=smtp
      - MAIL_HOST=mailtrap.io
      - MAIL_PORT=587
      - MAIL_USERNAME=null
      - MAIL_PASSWORD=null
      - MAIL_ADDRESS=null
      - MAIL_NAME=null
      - MAIL_ENCRYPTION=tls
    depends_on:
      - postgres
    restart: on-failure
